using System;

namespace Utilities
{
    public class Statements
    {
        public String GETQUOTESTOPROCESS = "SELECT TOP {0} a.Fecha_Hora_Creacion ,a.Fecha_Hora_Actualizacion ,a.[idcliente] ,a.nombre ,a.[territorio] , 0 AS Nuevo ,a.[calle] ,a.[colonia] ,a.[localidad] ,a.[ciudad] ,a.[estado] ,a.[pais] , a.codigopostal ,a.agente ,a.gps ,a.[tax] ,a.porcentajededescuento ,a.[fechadeentrega] ,a.[EventoKey] ,a.[Folio] ,a.estatusinterfaz , a.probabilidaddecierre ,'' AS Comentarios ,a.[Estatus] FROM dbo.LI_cotizaciones a WHERE Fecha_Hora_Creacion > '20180528' AND estatusinterfaz = 1 ORDER BY Fecha_Hora_Creacion DESC;";
        public String GETPRICELIST = "SELECT ListCode FROM DBE10SERVER.ERP10DB.dbo.PriceLst WHERE Company = 'TT';";
        public String UPDLICLIENTES = "INSERT INTO dbo.LI_clientes ([Registro_Key] ,[Usuario_Key] ,[Fecha_Hora_Creacion] ,[Fecha_Hora_Actualizacion] ,[Fecha_Hora_Eliminacion] ,[idcliente] ,[nombre] ,[idruta] ,[rfc] ,[limitedecredito] ,[plazo] ,[tipofacturacion] ,[estadocrediticio] ,[consolidacionpedidos] ,[correoelectronico] ,[numerocliente] ,[idagente] ,[listapreciosprimaria] ,[listapreciossecundaria] ,[gps] ,[zona] ,[tipo] ,[idorganizacion] ,[territorio] ,[calle] ,[colonia] ,[localidad] ,[ciudad] ,[estado] ,[pais] ,[codigopostal] ,[tax]) SELECT NEWID() AS Registro_Key ,[MS_tunneltek].dbo.ObtenerUsuarioKey([IDAgente])	AS [Usuario_Key] ,GETDATE()	AS [Fecha_Hora_Creacion] ,NULL AS [Fecha_Hora_Actualizacion] ,NULL AS [Fecha_Hora_Eliminacion] ,[IDcliente] AS [idcliente] ,[Nombre] AS [nombre] ,[IDRuta] AS [idruta] ,[RFC] AS [rfc] ,[LimiteDeCredito] AS [limitedecredito] ,[Plazo] AS [plazo] ,[TipoFacturacion] AS [tipofacturacion] ,[EstadoCrediticio] AS [estadocrediticio] ,[ConsolidacionPedidos] AS [consolidacionpedidos] ,[CorreoElectronico] AS [correoelectronico] ,[NumeroCliente] AS [numerocliente] ,[IDAgente] AS [idagente] ,[ListaPreciosPrimaria] AS [listapreciosprimaria] ,[ListaPreciosSecundaria] AS [listapreciossecundaria] ,[GPS] AS [gps] ,[Zona] AS [zona] ,CASE WHEN [Tipo] = 'CUS' THEN 'Cliente'WHEN [Tipo] = 'PRO'	THEN 'Prospecto'ELSE '' END AS [tipo] ,'' AS [idorganizacion] ,[IDRuta] AS [territorio] ,[calle] AS [calle] ,[colonia] AS [colonia] ,[localidad] AS [localidad] ,[ciudad] AS [ciudad] ,[estado] AS [estado] ,[pais] AS [pais] ,[codigopostal] AS [codigopostal] ,[ID_Iva] AS [tax] FROM  [DBE10SERVER].[ERP10DB].[dbo].[TT_Clientes] cl WHERE [MS_tunneltek].dbo.ObtenerUsuarioKey([IDAgente]) IS NOT NULL AND [IDCliente] = '{0}';";
        public String UPDSTATUSINTERFAZ = "UPDATE dbo.LI_cotizaciones SET estatusinterfaz = {0} WHERE eventokey = '{1}' AND folio = {2} AND idcliente = '{3}';";
        public String GETNEXTID = "SELECT MAX(CAST(c.CustID AS NUMERIC(10,0))) FROM DBE10SERVER.ERP10DB.dbo.Customer c WHERE c.Company = 'TT' ;";
    }
}
